### PR TITLE
capitalize

### PR DESCRIPTION
**Pull request by makandre**
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>

Fix capitalization as suggested in https://github.com/eclipse/codewind-docs/pull/518#discussion_r402578505

### CODE REVIEW

**Comment by makandre** [comment]
@sishida Could you merge this?

**Review by sishida — APPROVED** [review]

**Comment by sishida** [comment]
@makandre I have approved this PR, but I cannot merge it. GitHub says, "Only those with write access to this repository can merge pull requests."

This `codewind` organization appears to be different from the `eclipse` organization where I am a committer.

**Review by hhellyer — APPROVED** [review]
LGTM - Just a fix for better readability.

**Review by tobespc — APPROVED** [review]
Lgtm

**Pull request merged**
