### PR TITLE
Use pino instead of log4js

### PR DESCRIPTION
**Pull request by sam-github**
Align with:
- [Reference Architecture](https://github.ibm.com/Michael-Dawson/Nodejs-reference-architecture/blob/master/logging.md)
- [Appsody](https://github.com/appsody/stacks/pull/546/commits/bff95ecb0048b357783540ff6d15064eea119783)

Fixes:
- https://github.ibm.com/runtimes/squad-node/issues/419

### CODE REVIEW

**Comment by sam-github** [comment]
Are there docs anywhere that describe the logging package used that I can PR into?

cc: @mhdawson @NikCanvin @sympatheticmoose

**Comment by BethGriggs** [comment]
Maybe ping @tobespc?

**Comment by mhdawson** [comment]
@BethGriggs is going to see if she can  catch Tobe in person, if not then I'll email him and  Tim deBoer to ask if we can get it landed.

**Review by tobespc — APPROVED** [review]
LGTM

**Pull request merged**
